name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Qt
        uses: qt-actions/setup-qt@v2
        with:
          qt-version: '6.x'
          host-os: linux
          target: desktop

      - name: Build tests
        run: |
          cd tests
          qmake UT-2-SHA512.pro
          make

      - name: Run tests
        run: |
          cd tests
          ./UT-2-SHA512
