name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: tests  

      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-qmake libqt5core5a libqt5network5 libqt5sql5 sqlite3

      - name: Build tests
        run: |
          cd tests/тест1
          qmake UT-2-SHA512.pro
          make

      - name: Run tests
        run: |
          cd tests/тест1
          ./UT-2-SHA512
